apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  interval: 5m
  chart:
    spec:
      chart: base
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: istio-base-values-base
      valuesKey: values-base.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  interval: 5m
  dependsOn:
    - name: istiod
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: istio-ingress
spec:
  releaseName: istio-ingress
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: gateway
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
