apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml

configMapGenerator:
  - name: istio-base-values-base
    namespace: istio-system
    files:
      - values-base.yaml

generatorOptions:
  disableNameSuffixHash: true
