apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  role: "${TF_K8S_NODE_ROLE_ARN}"
  amiFamily: AL2 # Amazon Linux 2
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${TF_CLUSTER_NAME}"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "${TF_CLUSTER_NAME}"
