apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karpenter
  namespace: karpenter
spec:
  releaseName: karpenter
  interval: 5m
  targetNamespace: karpenter
  timeout: 10m
  chartRef:
    kind: OCIRepository
    name: karpenter
    namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: karpenter-values-base
      valuesKey: values.yaml
    - kind: ConfigMap
      name: karpenter-values-terraform
      valuesKey: values.yaml
