apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alb-controller
  namespace: kube-system
spec:
  releaseName: alb-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: 1.14.1
      sourceRef:
        kind: HelmRepository
        name: alb-controller
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: alb-controller-base-values-base
      valuesKey: values.yaml
    - kind: ConfigMap
      name: alb-controller-base-values-terraform
      valuesKey: values.yaml
