apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-repository.yaml
  - helm-release.yaml

configMapGenerator:
  - name: alb-controller-values-base
    namespace: kube-system
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
