apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/addons/dev
  prune: true
  dependsOn:
    - name: crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    value:
      substituteFrom:
        - kind: ConfigMap
          name: cluster-vars-terraform
