"apiVersion": "kustomize.toolkit.fluxcd.io/v1"
"kind": "Kustomization"
"metadata":
  "name": "flux-system-crds"
  "namespace": "flux-system"
"spec":
  "interval": "10m0s"
  "path": "./k8s/clusters/dev"
  "prune": "true"
  "sourceRef":
    "kind": "GitRepository"
    "name": "flux-system"
