apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: headlamp
  namespace: headlamp
spec:
  parentRefs:
    - name: gateway-api
      kind: Gateway
      sectionName: http
  hostnames:
    - ${TF_HEADLAMP_HOSTNAME}
  rules:
    - backendRefs:
        - name: headlamp
          port: 80
          weight: 1
