apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - oci-repository.yaml
  - helm-release.yaml
  - ec2-node-class.yaml
  - node-pool.yaml

configMapGenerator:
  - name: karpenter-values-base
    namespace: karpenter
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
