apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: headlamp-oidc
  namespace: headlamp
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secrets-manager-provider
    kind: ClusterSecretStore
  target:
    name: headlamp-oidc
    creationPolicy: Owner
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: "${TF_HEADLAMP_SECRET_MANAGER_ARN}"
        property: clientID
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: "${TF_HEADLAMP_SECRET_MANAGER_ARN}"
        property: clientSecret
    - secretKey: OIDC_ISSUER_URL
      remoteRef:
        key: "${TF_HEADLAMP_SECRET_MANAGER_ARN}"
        property: issuerURL
    - secretKey: OIDC_SCOPES
      remoteRef:
        key: "${TF_HEADLAMP_SECRET_MANAGER_ARN}"
        property: scopes
