apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - external-secrets.yaml
  - cluster-role-binding.yaml
  - http-route.yaml

configMapGenerator:
  - name: headlamp-values-base
    namespace: headlamp
    files:
      - values.yaml

generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
