apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: istio-system
spec:
  releaseName: istio-base
  driftDetection:
    mode: enabled
    ignore:
      - paths: [""]
        target:
          kind: ValidatingWebhookConfiguration
          name: istiod-default-validator
  interval: 5m
  chart:
    spec:
      chart: base
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: istio-base-values-base
      valuesKey: values-base.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: istio-system
spec:
  releaseName: istiod
  driftDetection:
    mode: enabled
  interval: 5m
  dependsOn:
    - name: istio-base
      namespace: istio-system
  chart:
    spec:
      chart: istiod
      version: 1.28.1
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: flux-system
